# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(default='VDK', max_length=10)),
                ('scope', models.CharField(default='SANITY', max_length=20)),
                ('startDate', models.DateField(verbose_name='Date time created')),
                ('endDate', models.DateField()),
                ('csvFile', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=10)),
                ('scope', models.CharField(max_length=20)),
                ('startDate', models.DateField(verbose_name='Date time created')),
                ('endDate', models.DateField()),
                ('csvFile', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='query',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sqadashboard.Search'),
        ),
    ]
