# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqadashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='genericString',
            field=models.CharField(default='END TO END TESTING', max_length=50),
        ),
        migrations.AddField(
            model_name='search',
            name='genericString',
            field=models.CharField(default='END TO END TESTING', max_length=50),
        ),
    ]
