# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-06 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import myproject.tims.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StreamName', models.FileField(storage=myproject.tims.models.OverwriteStorage(), upload_to='')),
                ('StreamType', models.CharField(max_length=100)),
            ],
        ),
    ]
