# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-08 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='Complexity',
            field=models.CharField(default='Not set', max_length=100),
        ),
        migrations.AddField(
            model_name='stream',
            name='Conformance',
            field=models.CharField(default='Not set', max_length=100),
        ),
        migrations.AddField(
            model_name='stream',
            name='ContainerFormat',
            field=models.CharField(default='Not set', max_length=100),
        ),
        migrations.AddField(
            model_name='stream',
            name='EncodedStreamType',
            field=models.CharField(default='Not set', max_length=100),
        ),
        migrations.AddField(
            model_name='stream',
            name='FrameCount',
            field=models.CharField(default='Not set', max_length=100),
        ),
        migrations.AddField(
            model_name='stream',
            name='Frames',
            field=models.CharField(default='Not set', max_length=100),
        ),
        migrations.AddField(
            model_name='stream',
            name='RawStreamType',
            field=models.CharField(default='Not set', max_length=100),
        ),
        migrations.AddField(
            model_name='stream',
            name='Resolution',
            field=models.CharField(default='Not set', max_length=100),
        ),
        migrations.AddField(
            model_name='stream',
            name='ScanType',
            field=models.CharField(default='Not set', max_length=100),
        ),
    ]
