# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-08 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tims', '0002_auto_20160908_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='Source',
            field=models.CharField(default='Not set', max_length=100),
        ),
    ]
